apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: nhussain
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: feature-toggle
        - secretRef:
            name: db-secret
        name: app-deployment
        image: registry.dev.afsmtddso.com/nhussain-harbor-project/db:2dbd18f-1fc30c5
        ports:
        - containerPort: 5000
